version: "3.9"
services:
  app:
    build: .
    ports:
      - "3333:3333"
    volumes:
      - .:/home/node/app
    depends:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456